blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Idea / Feature request
    url: ../../discussions/new?category=ideas
    about: Suggest an idea to improve PrestaShop
  - name: ğŸ™ I need help
    url: ../../discussions/new?category=q-a
    about: If you have questions or need help
