name: Lint
on: [ push, pull_request ]
jobs:
  stylelint_prettier:
    name: Stylelint & Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Run Prettier check command
      - name: Run Prettier check
        run: |
          npm run prettier || {
            echo "::error::Prettier check failed. Run 'npm run prettier:fix' to format your code."
            exit 1
          }

      # Run Stylelint check command
      - name: Run Stylelint check
        run: |
          npm run stylelint || {
            echo "::error::Stylelint check failed. Run 'npm run stylelint:fix' to autofix issues."
            exit 1
          }
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Lint js
        run: npm ci && npm run lint
